#%RAML 0.8
title: plumbagoAirlines
version: 1.0

traits: 
  - hasFlightsByCitiesQueryParams: !include traits/queryParams/getFlightsByCitiesQueryParams.raml
  - hasFlightsByCitiesResponse: !include traits/responses/getFlightsByCitiesResponse.raml
  - hasCommonErrorResponse: !include traits/responses/commonErrorResponse.raml
  - hasSeatBookingResponse: !include traits/responses/seatBookingResponse.raml

/plumbagoAirlineFlights:
  displayName: SearchFlights
  description: This API provides the details of flights
  /byCities:
    displayName: SearchFlightsByCities
    description: This API provides the list of flights between the cities as per the query parameters.
    get:
      is: [hasFlightsByCitiesQueryParams,hasFlightsByCitiesResponse,hasCommonErrorResponse]
  /seatBooking:
    displayName: seatBooking
    description: This API books the seat of flights
    post:
      is: [hasCommonErrorResponse,hasSeatBookingResponse]
      body: 
        application/json:
          example: !include examples/requestExamples/seatBookingRequest.json