#%RAML 0.8 Trait
responses:
  400:
    description: Bad Request.
    body:
      application/json:
        example: !include ../../examples/responseExamples/400-ResponseExample.json
  404:
    description: Method Not Allowed.
    body:
      application/json:
        example: !include ../../examples/responseExamples/404-ResponseExample.json
  415:
    description: Unsupported media type. The server is refusing to service the request because the format of the request is in a format not supported by the requested resource for the requested method.
    body:
      application/json:
        example: !include ../../examples/responseExamples/415-ResponseExample.json
  500:
    description: Internal Server Error -given that when an unexpected condition was encountered and no more specific message is suitable.
    body:
      application/json:
        example: !include ../../examples/responseExamples/500-ResponseExample.json
  502:
    description: Internal Server Error -given that when an unexpected condition was encountered and no more specific message is suitable.
    body:
      application/json:
        example: !include ../../examples/responseExamples/502-ResponseExample.json