#%RAML 0.8 Trait
responses:
  200:
    description: OK - This method returns the flight details based on given Cities.
        
    body:
      application/json:
        example: !include ../../examples/responseExamples/getFlightsByCitiesResponse.json
        