#%RAML 0.8 seatBookingResponse
responses:
  200:
    description: OK - Seat Booking was successful.
        
    body:
      application/json:
        example: !include ../../examples/responseExamples/seatBookingResponseExample.json